// <auto-generated />
using System;
using EventOne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventOne.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241006011745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EventOne.Models.Drivers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("drivers_pk_id");

                    b.ToTable("drivers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a34cadab-a2d9-4180-abad-987aa96e88ef"),
                            FirstName = "Bryan",
                            LastName = "Canon",
                            LicenseNumber = "KS0-34KSDFGSD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
